openapi: 3.0.2 # required
info: # requried
  version: '1.0'
  title: Open API3
  description: OpenAPI course
  termsOfService: http://example.tos.com/tos
  contact:
    name: Kumar Vaibhav
    url: http://myweb.com
    email: vaibhav.cs.kumar@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: https://dev.example.com
    description: Dev server
  - url: https://qa.example.com
    description: QA server
  - url: https://prod.example.com
    description: Prod Server
paths:
  /v1/customers:
    get:
      tags: 
        - Customers # Grouping together
      operationId: getAllCustomersV1 # this is used by code gens
      summary: List all customer
      description: Get all customer in system
      parameters: 
        - $ref: "#/components/parameters/PageNumberParam"
        - $ref: "#/components/parameters/PageSizeParam"
          
      responses: # list of responses
        '200':
          description: List of customers
          content:
            application/json:
              schema: #reponse type this can be another object
                $ref: "#/components/schemas/CustomerPagedList"
    post:
      tags: 
        - Customers
      summary: Create a new customer
      description: Add anew customer to the system
      operationId: postCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: "Customer created"
          headers:
            Location:
              schema:
                type: string
                format: uri
                description: the location of created resource in Location header
                example: http://example.com/v1/customers/{assignedId}
  /v1/customers/{customerId}:
    get:
      tags: 
        - Customers # Grouping together
      operationId: getCustomerByIdV1 # this is used by code gens
      summary: Get single customerdetails
      description: Get complete  description of a **customer**
      parameters:
        - name: customerId # this should match as it is in path else it won't match up
          in: path
          required: true
          description: Id of customer
          schema:
            type: string
            format: uuid
            description: uuid is a system generated value and it is hard to gess the next one
      responses:
        '200':
          description: response when customer data is found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /v1/beers:
    get:
      tags: 
        - Beer # Grouping together
      operationId: getAllBeersV1 # this is used by code gens
      summary: Get all beers in system
      description: Find all beers in system
      parameters: 
        - $ref: "#/components/parameters/PageNumberParam"
        - $ref: "#/components/parameters/PageSizeParam"
      responses:
        '200':
          description: List of Beers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BeerPagedList"
                      
        '404':
          description: Beers not found
  /v1/beers/{beerId}:
    get:
      tags: 
        - Beer
      operationId: getBeerByIdV1 # this is used by code gens
      summary: Get details of specified beer
      description: Get details of single **beer**
      parameters: 
        - name: beerId
          description: beer id to be found
          in: path # indicates path param
          required: true # requied true is mandatory for required
          schema:
            type: string
            format: uuid
            description: uuid is a system generated value
      responses:
        '200':
          description: found beer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Beer'
components:
  parameters:
    PageNumberParam:
      name: pageNumber
      in: query
      required: false
      description: Page number to be fetched
      schema:
        type: integer
        format: int32
        default: 0
    PageSizeParam:
      name: pageSize
      in: query
      required: false
      description: Number of records to be fetched
      schema:
        type: integer
        format: int32
        default: 25
        maximum: 100
  schemas:
    Address:
      type: object
      description: address object
      properties:
        line1:
          type: string
          example: 123
        city:
          type: string
          example: BLR
        stateCode:
          type: string
          minLength: 2
          maxLength: 2
          description: 2 letter state code
          # enum: [AL, AK, AZ, AR, CA] one way handle enum
          enum: 
            - AL
            - AK
            - AZ
            - AR
            - CA
        zipcode:
          type: string
          example: 560043
    Customer:
      type: object
      description: customer object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true # readonly is a property which says it should not be supplied by the requester but may or may not be set by the server it is opposite of writeOnly
        firstName:
          type: string
          minLength: 2
          maxLength: 100
          example: Kumar # this is example value
        lastName:
          type: string
          minLength: 2
          maxLength: 100
          example: Vaibhav #this is example value
        address:
          $ref: "#/components/schemas/Address"
    CustomerList:
      type: array
      minItems: 1
      maxItems: 100
      description: List of customers
      items:
        $ref: "#/components/schemas/Customer"
    Brewery:
      type: object
      description: Brewery producing this
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
          description: Name of the brewery
          example: Titos
        location:
          type: string
          minLength: 2
          maxLength: 100
          description: The city of the brewery
          example: BLR
    Beer:
      type: object
      description: beer object
      properties:
        beerName:
          type: string
          minLength: 2
          maxLength: 100
          description: name of the beer
          example: Carlsberg
        style:
          type: string
          minLength: 2
          maxLength: 20
          enum: 
            - ALE
            - PALE_ALE
            - IPA
            - WHEAT
            - LAGER
          description: style of the beer
        price:
          type: number
          format: float # define the subtype
          minimum: 0.1
          description: price of the beer
          example: 10.99
        quantityOnHand:
          type: integer
          format: int32 # define the subtype
          minimum: 1
          maximum: 500
          description: Quantity to be held
          example: 250
        brewery:
          $ref: "#/components/schemas/Brewery"
    BeerList:
      type: array
      items:
        $ref: "#/components/schemas/Beer"
    BeerPagedList:
      type: object
      allOf: # demonstrating inheritence
        - $ref: "#/components/schemas/PagedResponse"
      properties:
        content:
          $ref: "#/components/schemas/BeerList"
    CustomerPagedList:
      type: object
      allOf: # demonstrating inheritence
        - $ref: "#/components/schemas/PagedResponse"
      properties:
        content:
          $ref: "#/components/schemas/CustomerList"
    PagedResponse:
      type: object
      properties:
        pageable:
          $ref: '#/components/schemas/PagedResponse_pageable'
        totalPages:
          type: integer
          format: int32
        last:
          type: boolean
        totalElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        numberOfElements:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/PagedResponse_pageable_sort'
        first:
          type: boolean
    PagedResponse_pageable_sort:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
    PagedResponse_pageable:
      type: object
      properties:
        sort:
          $ref: '#/components/schemas/PagedResponse_pageable_sort'
        offset:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
